# Generated by Django 3.1.2 on 2020-10-11 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='namne')),
                ('head_img', models.CharField(blank=True, max_length=256, verbose_name='head_img_path')),
                ('c_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='c_time')),
                ('arrts', models.PositiveIntegerField(default=0, verbose_name='attrs')),
            ],
        ),
    ]
