# Generated by Django 3.1.2 on 2020-10-11 14:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('release_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='release_time')),
                ('release_state', models.PositiveIntegerField(default=0, verbose_name='release_state')),
                ('path', models.CharField(blank=True, max_length=256, verbose_name='path')),
                ('read_count', models.PositiveIntegerField(default=0, verbose_name='read_count')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='title')),
                ('teg_category', models.PositiveIntegerField(default=0, verbose_name='teg_category')),
                ('label_set', models.CharField(blank=True, max_length=300, verbose_name='label_set')),
                ('author_name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('keywords', models.CharField(max_length=300, verbose_name='keywords')),
                ('doc_format', models.CharField(blank=True, max_length=20, verbose_name='doc_format')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('c_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='c_time')),
                ('content', models.CharField(blank=True, max_length=256, verbose_name='content')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
                ('reviewer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
